FROM python:3.9-slim

WORKDIR /app

ADD main.py .
ADD requirements.txt .
aDD tests.py .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt
    
RUN python -m unittest tests.py

ENTRYPOINT ["python", "main.py"]